from ck_ab_gst import ck_ab_gst

class ck_video(ck_ab_gst):

    def test(self):
        pipeline = "v4l2src device={dev} num-buffers=3 ! jpegdec ! fakesink".format(dev=self.args.video)
        self.run_pipeline(pipeline)

if __name__=='__main__':
    t = ck_video()
    t.main()


"""
# gst-launch-1.0 v4l2src num-buffers=3 ! jpegdec ! fakesink

good:
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 0:00:00.140227228
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

bad:
Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
ERROR: from element /GstPipeline:pipeline0/GstJpegDec:jpegdec0: Failed to decode JPEG image
Additional debug info:
gstjpegdec.c(1194): gst_jpeg_dec_handle_frame (): /GstPipeline:pipeline0/GstJpegDec:jpegdec0:
Decode error #62: Invalid JPEG file structure: SOS before SOF
Execution ended after 0:00:00.495845910
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

"""
